name: CI
on:
  push: { branches: ["main"] }
  pull_request: { branches: ["main"] }
jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - run: npm ci || npm install
      - run: npm run lint || npx eslint . || echo "no lint script"
      - run: npm run type-check || npx tsc -noEmit || echo "no ts"
      - run: npx cspell "**/*" || echo "::warning title=cspell::Spelling issues (see log)"
      - run: npm run build || echo "no build script"
