name: Update TODO timestamp
on:
  push:
    branches: [ main ]
jobs:
  touch_todo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: node scripts/update-todo-timestamp.mjs
      - run: |
          if git diff --quiet; then
            echo "No changes"
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add TODO.md
            git commit -m "chore(todo): auto-update timestamp [skip ci]"
            git push
          fi
